name: Discord Event Notify

on:
  schedule:
    - cron: '0 7 * * 6'
    - cron: '0 13 * * 6'
    - cron: '33 13 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check week and send webhook
        run: |
          TZ=Asia/Tokyo
          DAY=$(TZ=$TZ date +%d)
          MONTH=$(TZ=$TZ date +%m)
          HOUR=$(TZ=$TZ date +%H)

          # テスト用（3月11日なら実行）
          if [[ "$MONTH" == "03" && "$DAY" == "11" ]]; then
            curl -H "Content-Type: application/json" \
            -d '{"content":"<@&1297168009743569029> \n> **会議通知（テスト）**\nテスト通知です。"}' \
            $WEBHOOK
            exit 0
          fi

          WEEK=$(( (10#$DAY - 1) / 7 + 1 ))

          if [ "$WEEK" = "1" ] || [ "$WEEK" = "3" ]; then
            if [ "$HOUR" = "07" ]; then
              curl -H "Content-Type: application/json" \
              -d '{"content":"<@&1297168009743569029> \n> **会議通知**\n会議開始の時間です。\n来れる方は集合してください。"}' \
              $WEBHOOK
            fi
          fi

          if [ "$WEEK" = "2" ] || [ "$WEEK" = "4" ]; then
            if [ "$HOUR" = "13" ]; then
              curl -H "Content-Type: application/json" \
              -d '{"content":"<@&1297168009743569029> \n> **会議通知**\n会議開始の時間です。\n来れる方は集合してください。"}' \
              $WEBHOOK
            fi
          fi
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
